# Generated by Django 5.1.7 on 2025-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapter_description',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
