# Generated by Django 5.1.7 on 2025-05-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_chapter_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapter_description',
        ),
    ]
